export interface GiftItem {
  id: number;
  name: string;
  price: number;
  image: string;
  category: string;
  reserved: boolean;
  amountReserved?: number;
}

export const gifts: GiftItem[] = [
  {
    id: 100,
    name: "Geladeira",
    price: 2800,
    image: "/geladeira.jpeg",
    category: "Cozinha",
    reserved: false,
    amountReserved: 0,
  },
  {
    id: 99,
    name: "Sofá",
    price: 1500,
    image: "/sofa.jpeg",
    category: "Casa",
    reserved: false,
    amountReserved: 0,
  },
  {
    id: 98,
    name: "Máquina de Lavar",
    price: 2400,
    image: "/maquina-lavar.jpeg",
    category: "Casa",
    reserved: false,
    amountReserved: 0,
  },
  {
    id: 97,
    name: "Fogão 4 bocas",
    price: 800,
    image: "/fogao.jpeg",
    category: "Cozinha",
    reserved: false,
    amountReserved: 0,
  },
  {
    id: 96,
    name: "Microondas Panasonic",
    price: 450,
    image: "/microondas.jpeg",
    category: "Cozinha",
    reserved: false,
    amountReserved: 200,
  },
  {
    id: 95,
    name: "Colibri Rack Bancada",
    price: 750,
    image: "/rack.webp",
    category: "Casa",
    reserved: false,
    amountReserved: 200,
  },
  {
    id: 94,
    name: "Panelas Brinox",
    price: 400,
    image: "/panelas.jpeg",
    category: "Cozinha",
    reserved: false,
    amountReserved: 0,
  },
  {
    id: 93,
    name: "Jogo Pratos Tramontina",
    price: 460,
    image: "/pratos.jpeg",
    category: "Mesa",
    reserved: false,
    amountReserved: 0,
  },

  {
    id: 92,
    name: "Airfrier Mondial",
    price: 230,
    image: "/airfrier.jpeg",
    category: "Cozinha",
    reserved: false,
  },
  {
    id: 91,
    name: "Liquidificador Mondial",
    price: 150,
    image: "/liquidificador.jpeg",
    category: "Cozinha",
    reserved: false,
  },
  {
    id: 90,
    name: "Ferro Vaporizador Black-Decker",
    price: 185,
    image: "/ferro.jpeg",
    category: "Quarto",
    reserved: false,
  },
  {
    id: 89,
    name: "Jogo de Facas",
    price: 85,
    image: "/facas.jpeg",
    category: "Cozinha",
    reserved: false,
  },
  {
    id: 88,
    name: "Organizador de Talheres",
    price: 75,
    image: "/organizador.jpeg",
    category: "Cozinha",
    reserved: false,
  },
  {
    id: 87,
    name: "Vassoura Rodo Esfregão",
    price: 160,
    image: "/mop.jpeg",
    category: "Casa",
    reserved: false,
  },
  {
    id: 86,
    name: "Potes Herméticos",
    price: 175,
    image: "/potes.jpeg",
    category: "Cozinha",
    reserved: false,
  },
  {
    id: 85,
    name: "Jogo de Copos",
    price: 65,
    image: "/copos.jpeg",
    category: "Mesa",
    reserved: false,
  },
  {
    id: 84,
    name: "Ventilador",
    price: 299,
    image: "/ventilador.jpeg",
    category: "Quarto",
    reserved: false,
  },
  {
    id: 83,
    name: "Tábua de cortar de bamboo",
    price: 59,
    image: "/tabua.jpeg",
    category: "Cozinha",
    reserved: false,
  },
  {
    id: 82,
    name: "2kg de picanha",
    price: 140,
    image: "/picanha.jpeg",
    category: "Cozinha",
    reserved: false,
  },
  {
    id: 81,
    name: "Jogo de cama",
    price: 60,
    image: "/jogo-cama.jpeg",
    category: "Quarto",
    reserved: false,
  },
  {
    id: 80,
    name: "Lingerie sexy para a noite de núpcias",
    price: 60,
    image: "/calcola.webp",
    category: "Casal",
    reserved: false,
  },
  {
    id: 79,
    name: "2 passagens para a lua (lua de mel)",
    price: 560,
    image: "/lua-de-mel.jpeg",
    category: "Casal",
    reserved: false,
    amountReserved: 0,
  },
  {
    id: 78,
    name: "TV 40 polegadas",
    price: 1200,
    image: "/tv.webp",
    category: "Casa",
    amountReserved: 0,
    reserved: false,
  },
  {
    id: 76,
    name: "Ar Condicionado",
    price: 670,
    image: "/ar-condicionado.jpg",
    amountReserved: 0,
    category: "Casa",
    reserved: false,
  },
  {
    id: 75,
    name: "Freezer Horizontal",
    price: 1800,
    image: "/freezer.webp",
    category: "Cozinha",
    amountReserved: 0,
    reserved: false,
  },
  {
    id: 74,
    name: "Mesa de Jantar",
    price: 1300,
    amountReserved: 0,
    image: "/mesa-jantar.webp",
    category: "Casa",
    reserved: false,
  },
  {
    id: 67,
    name: "Forno Elétrico",
    price: 450,
    image: "/forno.jpeg",
    category: "Cozinha",
    reserved: false,
  },
  {
    id: 66,
    name: "Purificador de Água",
    price: 350,
    image: "/agua.jpeg",
    category: "Cozinha",
    reserved: false,
  },
  {
    id: 65,
    name: "Batedeira",
    price: 200,
    image: "/batedeira.jpeg",
    category: "Cozinha",
    reserved: false,
  },
  {
    id: 63,
    name: "Cafeteira Elétrica",
    price: 320,
    image: "/cafeteira.jpeg",
    category: "Cozinha",
    reserved: false,
  },
  {
    id: 62,
    name: "Panela Elétrica",
    price: 180,
    image: "/panela.jpeg",
    category: "Cozinha",
    reserved: false,
  },
  {
    id: 61,
    name: "Kit Churrasco",
    price: 120,
    image: "/churrasco.jpeg",
    category: "Cozinha",
    reserved: false,
  },
  {
    id: 60,
    name: "Kit Fondue",
    price: 170,
    image: "/fondue.jpeg",
    category: "Casal",
    reserved: false,
  },
  {
    id: 59,
    name: "Kit Sushi",
    price: 130,
    image: "/sushi.jpeg",
    category: "Cozinha",
    reserved: false,
  },
  {
    id: 58,
    name: "Kit Hambúrguer",
    price: 150,
    image: "/burger.jpeg",
    category: "Cozinha",
    reserved: false,
  },
  {
    id: 57,
    name: "Kit Pizza",
    price: 80,
    image: "/pizza.jpeg",
    category: "Cozinha",
    reserved: false,
  },
  {
    id: 56,
    name: "Taco Inflável Anti Marido",
    price: 45,
    image: "/taco.jpeg",
    category: "Casal",
    reserved: false,
  },
  {
    id: 54,
    name: "Apito Anti Ronco",
    price: 20,
    image: "/apito.jpeg",
    category: "Casal",
    reserved: false,
  },
  {
    id: 53,
    name: "Botão Modo Silêncio do Marido",
    price: 35,
    image: "/silencio.jpeg",
    category: "Casal",
    reserved: false,
  },
  {
    id: 52,
    name: "Campainha para chamar o cônjuge",
    price: 25,
    image: "/campainha.jpeg",
    category: "Casal",
    reserved: false,
  },
  {
    id: 51,
    name: "Placa 'Quem manda aqui sou eu'",
    price: 20,
    image: "/placa.jpeg",
    category: "Casal",
    reserved: false,
  },
  {
    id: 50,
    name: "Jogo de Toalhas",
    price: 120,
    image: "/toalhas.jpeg",
    category: "Casa",
    reserved: false,
  },
  {
    id: 49,
    name: "Tapete Sala",
    price: 200,
    image: "/tapete.jpeg",
    category: "Casa",
    reserved: false,
  },
  {
    id: 48,
    name: "Relógio de Parede",
    price: 120,
    image: "/relogio.jpeg",
    category: "Casa",
    reserved: false,
  },
  {
    id: 47,
    name: "Travesseiros",
    price: 160,
    image: "/travesseiro.jpeg",
    category: "Quarto",
    reserved: false,
  },
  {
    id: 46,
    name: "Cesto de Roupas",
    price: 90,
    image: "/cesto.jpeg",
    category: "Casa",
    reserved: false,
  },
  {
    id: 45,
    name: "Frigideira Antiaderente",
    price: 140,
    image: "/frigideira.jpeg",
    category: "Cozinha",
    reserved: false,
  },

  {
    id: 44,
    name: "Jarra de Suco",
    price: 70,
    image: "/jarra.jpeg",
    category: "Mesa",
    reserved: false,
  },
  {
    id: 43,
    name: "Kit Temperos",
    price: 70,
    image: "/temperos.jpeg",
    category: "Cozinha",
    reserved: false,
  },
  {
    id: 42,
    name: "Pano de Prato Premium",
    price: 50,
    image: "/pano.jpeg",
    category: "Cozinha",
    reserved: false,
  },
  {
    id: 41,
    name: "Jogo Americano",
    price: 85,
    image: "/americano.jpeg",
    category: "Mesa",
    reserved: false,
  },

  {
    id: 40,
    name: "Kit Banheiro",
    price: 110,
    image: "/banheiro.jpeg",
    category: "Casa",
    reserved: false,
  },
  {
    id: 39,
    name: "Lixeira Inox",
    price: 150,
    image: "/lixeira.jpeg",
    category: "Casa",
    reserved: false,
  },
  {
    id: 38,
    name: "Espelho Decorativo",
    price: 210,
    image: "/espelho.jpeg",
    category: "Casa",
    reserved: false,
  },
  {
    id: 37,
    name: "Velas Decorativas",
    price: 90,
    image: "/velas.jpeg",
    category: "Casa",
    reserved: false,
  },

  {
    id: 36,
    name: "Kit Vinho",
    price: 150,
    image: "/vinho.jpeg",
    category: "Casal",
    reserved: false,
  },
  {
    id: 35,
    name: "Algemas de Brincadeira",
    price: 30,
    image: "/algema.jpeg",
    category: "Casal",
    reserved: false,
  },

  ...Array.from({ length: 34 }, (_, i) => ({
    id: 34 - i,
    name: `Vale Presente Casamento ${34 - i}`,
    price: 50,
    image: "/vale.jpeg",
    category: "Casal",
    reserved: false,
  })),
];
